# Generated by Django 5.1.6 on 2025-02-20 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diskover_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='route_color',
            new_name='routeColor',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='route_marker',
            new_name='routeMarker',
        ),
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='diskover_api.category'),
        ),
    ]
