# Generated by Django 5.1.6 on 2025-04-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diskover_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='route_marker',
            field=models.CharField(blank=True, db_column='routeMarker', max_length=260, null=True),
        ),
    ]
