# Generated by Django 5.1.6 on 2025-02-20 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diskover_api', '0002_rename_route_color_category_routecolor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='routeColor',
            new_name='route_color',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='routeMarker',
            new_name='route_marker',
        ),
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='diskover_api.category'),
        ),
    ]
