# Generated by Django 5.1.6 on 2025-04-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diskover_api', '0002_alter_category_route_marker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='route_marker',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
    ]
